name: gha-migration/manual_check
on:
  push:
  workflow_dispatch:
concurrency:
  group: "${{ github.ref }}"
  cancel-in-progress: true
jobs:
  build_job:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:22.04
    if: ${{ github.event_name }} == "push"
    timeout-minutes: 60
    env:
      APP_NAME: demo application
    steps:
    - uses: actions/checkout@v4.1.0
      with:
        fetch-depth: 20
        lfs: true
    - run: echo "Building $APP_NAME..."
    - run: echo "Docker Image Build Successful" > build.txt
    - run: cat build.txt
    - uses: actions/upload-artifact@v4.1.0
      if: success()
      with:
        name: "${{ github.job }}"
        path: build.txt
  test_job:
    needs: build_job
    runs-on: ubuntu-latest
    container:
      image: ubuntu:22.04
    if: ${{ github.event_name }} == "push"
    timeout-minutes: 60
    env:
      APP_NAME: demo application
    steps:
    - uses: actions/checkout@v4.1.0
      with:
        fetch-depth: 20
        lfs: true
    - uses: actions/download-artifact@v4.1.0
    - run: echo "Testing the application..."
    - run: cat build.txt
    - run: echo "Test completed successfully" > test.txt
    - run: cat test.txt
    - uses: actions/upload-artifact@v4.1.0
      if: success()
      with:
        name: "${{ github.job }}"
        path: test.txt
  deploy_job:
    needs: test_job
    runs-on: ubuntu-latest
    container:
      image: ubuntu:22.04
    if: ${{ github.event_name }} == "push"
    timeout-minutes: 60
    env:
      APP_NAME: demo application
    steps:
    - uses: actions/checkout@v4.1.0
      with:
        fetch-depth: 20
        lfs: true
    - uses: actions/download-artifact@v4.1.0
    - run: echo "Deploying..."
    - run: cat test.txt
    - run: echo "Deployment successful" > deploy.txt
    - run: cat deploy.txt
    - run: echo "Deployment completed"
    - uses: actions/upload-artifact@v4.1.0
      if: success()
      with:
        name: "${{ github.job }}"
        path: deploy.txt
